### ISSUE TITLE
Demo not working anymore (?)

### ISSUE THREAD

**Issue by valerio-bozzolan** [sunng87/heatcanvas#44]
Hi all! I've clicked on the demo link in the README but it's not working anymore. Are you aware of that?

http://sunng87.github.com/heatcanvas

I was just interested in add an operational demo link from this page:

https://leafletjs.com/plugins.html

Thank you so much for your work on this plugin! :)

**Comment by sunng87** [comment]
It seems github stopped using github.com for pages. You can access the demo via https://sunng87.github.io/heatcanvas

I will update the readme for new link

**Comment by sunng87** [comment]
Fixedin ccb5132

**Comment by valerio-bozzolan** [comment]
Amazing!

@sunng87 

Also I noticed that the link "Watch the source code on github." also maybe needs an update from here:

https://sunng87.github.io/heatcanvas/

Thank you so much!
